### ISSUE TITLE
Prepare to release the first stable version on October 31st.

### ISSUE THREAD

**Issue by overcat** [StellarCN/py-stellar-base#157]
Suggestions are welcome.

**Comment by overcat** [comment]
@shredding I want to collect some feedback for the 0.2.x version, and the 0.2.x version can smoothly update to 1.0.

**Comment by shredding** [comment]
If I can add my 2cents of minor things:

- my overall experience is really great
- the errors are too generic and it would be great if we'd have a `StellarBaseException` for everything and maybe even more specific exceptions at some points to give a chance for a more granular recover. Since this is `Exception` atm, it may be added without breaking stuff.
- `:params:` are sometimes a bit off in the docs
- it's sometimes `keypair` and sometimes `key_pair`.

I'd like to add, but that would be breaking, that the signing process would benefit from abstraction a lot. The current `Keypair` implementation is making the assumption that secrets are available to the server. That's e.g. not given in my setup where we do use a hashicorp vault cluster for signing.

It's not a big pull off, as we roll our own `Keypair` subclass with the gist of 

```
    def sign(self, data):
        """
        Signs with an external vault.

        :param byte data:
        :returns byte:
        """
        b64_data = base64.b64encode(data).decode()

        try:
            payload = get_client().transit_sign_data(self.vault_key, b64_data)
            b64_signature = payload['data']['signature'].split(':')[-1]
            return base64.b64decode(b64_signature)
        except InvalidRequest as exc:
            logging.error(f'Invalid vault request: {str(exc)} for key {self.vault_key}.')
            raise
```

... but it requires a bit off lifting to avoid all the places where a secret is assumed.

This may be worked around if we'd have some kind of settings where we could choose implementations based on our own key management and a bit of unifying of some of the APIs.

If you're up to the idea, i would play around a bit and make a PR, but i'm kind of busy atm at work, so it may take some time, but looking forward it would help me a lot having this abstraction as part of the library itself.

**Comment by overcat** [comment]
@shredding Hi, Thanks for your suggestion, if you can submit a PR about Exception, I will be very grateful to you. 

I don't understand much about Keypair module, I don't want to increase the complexity of the Keypair module. I also believe that there are some things that need to be implemented by the user, It is impossible for SDK to do everything.

Thanks again.

**Comment by Auha** [comment]
I am new here, and I just saw this issue. Would you guys recommend using this SDK for a production system in lieu of the officially supported SDK's?

**Comment by tempofr** [comment]
SDF has reviewed the code.

It is production ready.

**Comment by shredding** [comment]
> @shredding Hi, Thanks for your suggestion, if you can submit a PR about Exception, I will be very grateful to you.

I'll see on what I can come up with within the next two weeks.

**Comment by tempofr** [comment]
Great... The suggestions can be rolled out after Oct 31 perhaps.

Mostly they all sound great especially cleaning up parameters...

Anthony BARKER | TEMPO FRANCE

**Comment by overcat** [comment]
@shredding Hi, thank you for your suggestion I hope it will be merged into the main branch before the stable released, so I submitted a pull request(#164) myself. Can you take a moment to review it? If you have other suggestions, please submit the code directly to the dev branch.

**Comment by shredding** [comment]
That looks great! Awesome.

**Comment by overcat** [comment]
The new version has been released. Thank you to all the people who have already contributed to py-stellar-base!
