### ISSUE TITLE
If you create a TransactionEnvelope from XDR, you can't set it to the mainnet server.

### ISSUE THREAD

**Issue by vitchor** [StellarCN/py-stellar-base#232]
Because the from_xdr() method, in transaction_envelope.py, doesn't send a "network_id" parameter.

**Comment by overcat** [comment]
Yes, this is a design flaw. Do you mind using our brand [new SDK v2](https://github.com/StellarCN/py-stellar-base/tree/v2)? This problem was solved in v2, check [here](https://github.com/StellarCN/py-stellar-base/blob/v2/stellar_sdk/transaction_envelope.py#L146).

If you want to use v1, please import XDR through [it](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/builder.py#L933), you can also choose to modify the [network_id](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/transaction_envelope.py#L41) in TransactionEnvelope object directly.
