### ISSUE TITLE
Tests for Horizon

### ISSUE THREAD

**Issue by Akuukis** [StellarCN/py-stellar-base#24]
Spent last 6 hours chasing bug that caused `Internal Server Error'` response, I though it was something in test-horizon but it turned out that requests.post() keyword `params =/= data` and it was not sending to it any tx at all.

So should write tests for Horizon class.

**Comment by manran** [comment]
:sweat:  very sorry . though it did work before.

**Comment by Akuukis** [comment]
It is weird because I also think it worked before. Maybe that was because of fork differences that is now deleted.

**Comment by HongxuChen** [comment]
I encountered a similar issue several months ago however I don't know the exact root cause. It seems that `params` is used for url encoding so presented by get (`get(url, params=None, **kwargs)`), while `data` is typical for post body (`post(url, data=None, json=None, **kwargs)`, `json` appears also for post body).
