### ISSUE TITLE
update challenge tx helpers for SEP-10 v1.3.0

### ISSUE THREAD

**Issue by overcat** [StellarCN/py-stellar-base#252]
https://github.com/stellar/django-polaris/issues/60
https://github.com/stellar/go/pull/2071

**Comment by leighmcculloch** [comment]
@overcat FYI that the stellar/go#2071 received some updates and changes to how the signatures get verified between when you opened this issue and when I merged it that you may be interested in 👀if you used it that PR as a reference when implementing #259.

**Comment by leighmcculloch** [comment]
@overcat I saw your questions over on stellar/go#2071 but I can't find the comments, so I'll reply here:

>We have verified the server's signature in ReadChallengeTx, is it necessary to verify it again here?>@leighmcculloch We have verified the server's signature in ReadChallengeTx, is it necessary to verify it again here?

The reason for this is because when verifying the signatures on a transaction against a list of signers we want to ensure that each signature is consumed exactly once, and each signer is matched at most once. We don't want this code to make any assumptions about the keys and how the signatures get generated to satisfy that requirement, and so we re-include the server key to validate that a signature gets matched to it, and doesn't get matched twice, once to it in the read call and once to a client key in the verify call. The fact that the server key is already checked in the ReadChallengeTx is happenstance, its good to check it in that function so that no party reads a challenge transaction that isn't signed by the server but the verify function is not relying on it for anything.

Thanks for asking, that was a great question.

**Comment by overcat** [comment]
@leighmcculloch Thank you for the detailed explanation.

**Comment by leighmcculloch** [comment]
@overcat It's so great that you implemented the changes to SEP-10 so quickly. I'm just getting a chance to take a look at the SEP-10 code. I looked over the code in these functions that are on the `master` branch (commit 43caa832968):

- `build_challenge_transaction`
- `read_challenge_transaction`
- `verify_challenge_transaction_signers`
- `verify_challenge_transaction_signed_by_client`
- `verify_challenge_transaction_threshold`
- `verify_challenge_transaction`
- `_verify_transaction_signatures`
- `_verify_te_signed_by`
- `example_verify_challenge_tx_threshold`

I love the example code and the comments, I'm not a Python developer and I was able follow with the code better with those :clap:.

I have some suggestions:

1. https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L39 `build_challenge_transaction ` uses the default timeout of 300ms, but it could be bumped to 900ms. We bumped it up in SEP-10 v1.3.0 to provide multi-sig accounts more time to walk through their often complex steps to sign the challenge. https://github.com/stellar/stellar-protocol/commit/ea0d7edc3bed84a24970c5fe5fc34993e6c97e48#diff-72480d0894ae2d1a31c229b64ad4c37bL84

1. https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L237 `verify_challenge_transaction_signed_by_client` looks very convenient, but I'm wondering if someone will use that by default because the name sounds like it will automatically verify the client signed the transaction. The name doesn't illude that it is only verifying the client's master key has signed and not that the client account has signed. This was a reason I left a function like this out of the Go SDK.

1. https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L194-L205 `verify_challenge_transaction_signers` has a comment saying it deduplicates the signers, but I don't see code doing that at the comment. https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L194 It looks like you do deduplication in another place further down in the same function, so maybe the comment is in the incorrect place. It can be worth removing duplicates early to prevent surprises in other code. But I couldn't see anything functional wrong with doing it this way if you preferred this.

1. https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L224-L234 `verify_challenge_transaction_signers` looks like it might succeed without exception if none of the non-server client signers are found. I think this is possible if the developer passes in only the server key as a signer. Is that right or is there an error? I think it'd be worth erroring in the case that the only signer found is the server key, or no signers were found.

1. https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L207-L212 https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L343-L347 `verify_challenge_transaction_signers` contains a comment saying it verifies all the signatures and signers together, but actually they get verified independently one at a time. The main distinction between these two approaches is that to do them together the signatures get matched to signers exactly once. If I'm reading the code correctly a signature could get matched more than once. In the case two signers ever produced the same signature (I don't know if this is possible) this code would count the signature twice. We don't make the that that's safe in the Go SDK and prevent a signature from being reused. Here's an example of how we prevent signature reuse in the Go SDK: https://github.com/stellar/go/blob/4268b29/txnbuild/transaction.go#L680. This is also true of `verify_challenge_transaction_signed_by_client` and so it could be good to have that function call `verify_challenge_transaction_signers` instead of `verify_challenge_transaction`. This was something that I added to the Go SDKs PR just before merging it, so there's a good chance this wasn't present when you took a look at it.

1. https://github.com/StellarCN/py-stellar-base/blob/43caa832968aa0874369c56c849e543923518292/stellar_sdk/sep/stellar_web_authentication.py#L138-L141 `read_challenge_transaction` doesn't validate that the base64 decoded data is exactly 48 bytes as some of the other SDKs do. This SDK will allow it to be 48, 49, or 50 bytes long. I cannot imagine a scenario where this will cause a meaningful issue, but FYI that this inconsistency exists.

Thanks!

cc @JakeUrban

**Comment by overcat** [comment]
@leighmcculloch Thank you for pointing out these issues.

For the second point, I want to keep the function, but we should rename it, do you have any suggestions?

**Comment by leighmcculloch** [comment]
>we should rename it, do you have any suggestions?

Maybe `verify_challenge_transaction_signed_by_client_master_key`. That matches the terminology used in the SEP and the docs about signing keys.

>I'm not sure if it is necessary to throw an exception, the function returns a list of
signers that were found, I think what to do with these signers should be left to the user, even if the list is empty.

That's a good point, but the main use case of this function is to verify that the challenge transaction is fully signed and a transaction not signed by the client other than the server's key in the case that the client has the servers key as a signer is likely going to be in error. This function and the other functions all raise exceptions in the cases where something is likely wrong so I think it should here too. I think the idea to just return what is found would be more applicable if the function wasn't intended for verifying a specific use case, and instead just for looking up signers generically.

**Comment by leighmcculloch** [comment]
@overcat Are you planning further PRs relating to the changes to SEP-10, or is this issue closable now? Let me know if you'd like me to 👀 anything else and I'm happy to.
