### ISSUE TITLE
Allow Trust

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [StellarCN/py-stellar-base#78]
hI, i have a simple API that make transactions between accounts, we have an Asset and we want to make transactions with it, the problem is that we need to "Allow Trust" every time when we created an account.
We need to allow our asset on automatic when we created and activated the account.

Any idea if in this library we can do this?

**Comment by juehai** [comment]
I think ideally you should wrap the changeTrust op into the process of when you are creating your account so that it will be one of the steps of your account creation.

To be clear, you should have your own library to control that each account is going to allow which asset, even the asset was created by yourself.
